#!/usr/bin/env bash
# Install nginx on your web01 server
# Nginx should be listening on port 80
# Nginx, when sent a GET request at its root /, must return a page that
# contains at least once the string "Holberton School"
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
