#!/usr/bin/env bash
# Fixes a container so that Nginx is running as the nginx user

# kill apache2 service/process
pkill apache2

# find and replace
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-enabled/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# chand permission and ownership
chmod 755 /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx/

#switch user and evoke nginx restart
su nginx -c 'service nginx restart'
