#!/usr/bin/env bash
# Configures domain zone to point all domain query to lb-01

FILE=answer_sec.txt

{
dig www.whoneeds.space | grep -A1 'ANSWER SECTION:'
dig lb-01.whoneeds.space | grep -A1 'ANSWER SECTION:'
dig web-01.whoneeds.space | grep -A1 'ANSWER SECTION:'
dig web-02.whoneeds.space | grep -A1 'ANSWER SECTION:'
} > $FILE

DOMAIN=$1
SUBDOMAIN=$2

if [$2 -eq 0]
then
    awk '/www/ {print ""}'
    awk '/www/'The subdomain www is a A record and points to 54.210.47.110
    The subdomain lb-01 is a A record and points to 54.210.47.110
    The subdomain web-01 is a A record and points to 34.198.248.145
    The subdomain web-02 is a A record and points to 54.89.38.100
