#!/usr/bin/env bash
# a Bash script that will display information about subdomains.
DOMAIN=$1
SUBDOMAIN=$2
FILE=answer_sec.txt

{
dig www.$1 | grep -A1 'ANSWER SECTION:'
dig lb-01.$1 | grep -A1 'ANSWER SECTION:'
dig web-01.$1 | grep -A1 'ANSWER SECTION:'
dig web-02.$1 | grep -A1 'ANSWER SECTION:'
} > $FILE

if [[ -n $2 ]]
then
    awk -v var="$SUBDOMAIN" "/$SUBDOMAIN/"'{print "The subdomain "var" is a "$4" record and points to "$5;}' $FILE
else
    awk '/www/ {print "The subdomain www is a "$4" record and points to "$5;}' $FILE
    awk '/lb-01/ {print "The subdomain lb-01 is a "$4" record and points to "$5;}' $FILE
    awk '/web-01/ {print "The subdomain web-01 is a "$4" record and points to "$5;}' $FILE
    awk '/web-02/ {print "The subdomain web-02 is a "$4" record and points to "$5;}' $FILE
fi
