#!/usr/bin/env bash
# Configures domain zone to point all domain query to lb-01

FILE=answer_sec.txt

{
dig www.whoneeds.space | grep -A1 'ANSWER SECTION:'
dig lb-01.whoneeds.space | grep -A1 'ANSWER SECTION:'
dig web-01.whoneeds.space | grep -A1 'ANSWER SECTION:'
dig web-02.whoneeds.space | grep -A1 'ANSWER SECTION:'
} > $FILE

DOMAIN=$1
SUBDOMAIN=$2

if [$2 -eq null]
then
    awk '/www/ {print "The subdomain www is a "$4" record and points to "$5;}' $FILE
    awk '/lb-01/ {print"The subdomain lb-01 is a "$4" record and points to "$5;}' $FILE
    awk '/web-01/ {print"The subdomain web-01 is a "$4" record and points to "$5;}' $FILE
    awk '/web-02/ {print"The subdomain web-02 is a "$4" record and points to "$5;}' $FILE
fi
