#!/usr/bin/env bash
# configures load balancer to two servers
sudo apt-get update
sudo apt-get install -y haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.copy
file=/etc/haproxy/haproxy.cfg

sudo sed -i '$a\\nlisten appname 0.0.0.0:80\n\tmode http\n\tstats enable' $file
sudo sed -i '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' $file
sudo sed -i '$a\\tserver 93-web-01 52.206.143.134:80\n\tserver 93-web-02 54.90.169.222:80' $file

sudo service haproxy start
