#!/usr/bin/env bash
# a Bash script that configures a Ubuntu server with the below requirements.
# Requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

# copy hosts to root w/ newname
sudo cp /etc/hosts ~/hosts.new

# adds localhost and facebook
sudo sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sudo sed -i '2i/8.8.8.8\tfacebook.com' ~/hosts.new

# force copy
sudo cp -f ~/hosts.new /etc/hosts
