#!/usr/bin/env bash

# update apt list and install ufw
sudo apt-get update
sudo apt-get -y install ufw

# blocks incoming traffic
sudo ufw default deny incoming

# grants permission to 22, 448, 80
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80

# turns on ufw
sudo ufw enable
