#!/usr/bin/env bash
# script that displays numbers from 1 to 20 and:
# "bad luck from China"
# "bad luck from Japan"
# "bad luck from Italy"
# use case statement
((i=1))
while ((i < 21));
do
case $i in
    5)
	echo "bad luck from China"
	;;
    10)
	echo "bad luck from Japan"
	;;
    18)
	echo "bad luck from Italy"
	;;
    esac
    echo $i
    ((i++))
done
